# Generated by Django 5.2.2 on 2025-08-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='site_logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(help_text='Use full international format, e.g., +2567XXXXXXX', max_length=20)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
