# Generated by Django 5.2.2 on 2025-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title or heading', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subheading or tagline', max_length=255, null=True)),
                ('description', models.TextField(help_text='Full description about the organization')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, help_text='Background or how it started', null=True)),
                ('image', models.ImageField(blank=True, help_text='An optional image (e.g., team photo, logo, etc.)', null=True, upload_to='about/')),
                ('team_members', models.TextField(blank=True, help_text='Enter names separated by commas. E.g. John, Sarah, Alex', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
