# Generated by Django 5.2.2 on 2025-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order of this step in the process')),
                ('step_title', models.CharField(help_text='Short title for this step', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of this step')),
                ('image', models.ImageField(blank=True, help_text='Optional illustration for the step', null=True, upload_to='how_it_works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['step_number'],
            },
        ),
    ]
