# Generated by Django 5.2.2 on 2025-08-08 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0004_howitworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='website',
            field=models.URLField(blank=True, help_text="Link to the organization's website", null=True),
        ),
    ]
