# Generated by Django 5.2.2 on 2025-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0005_aboutus_created_at_aboutus_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='backgroundimage',
            field=models.ImageField(blank=True, help_text='Optional background image for the site', null=True, upload_to='backgrounds/'),
        ),
    ]
