# Generated by Django 5.2.2 on 2025-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0006_sitesettings_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='backgroundimage2',
            field=models.ImageField(blank=True, help_text='Optional background image for the site', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcomemsg',
            field=models.CharField(blank=True, help_text='Welcome To PaperFlow Site', max_length=1000, null=True),
        ),
    ]
