# Generated by Django 5.2.2 on 2025-08-09 06:51

import django.db.models.deletion
import paperflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0007_sitesettings_backgroundimage2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('course_type', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20)),
                ('duration_years', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['semester_number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='paperflow.course')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('course', 'year')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='paperflow.faculty'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=paperflow.models.note_file_path)),
                ('note_type', models.CharField(choices=[('lecture', 'Lecture Notes'), ('assignment', 'Assignment'), ('exam', 'Past Exam'), ('reference', 'Reference Material'), ('other', 'Other')], default='lecture', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='paperflow.semester')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='paperflow.academicyear')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('academic_year', 'level')},
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='paperflow.yearlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('faculty', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year_level', 'semester_number')},
        ),
    ]
