# Generated by Django 5.2.2 on 2025-08-12 08:17

import django.db.models.deletion
import django.utils.timezone
import paperflow.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflow', '0008_course_faculty_semester_academicyear_course_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='has_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Requires payment to view/download'),
        ),
        migrations.AddField(
            model_name='note',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Auto-generated preview file (first page + sample question)', null=True, upload_to=paperflow.models.preview_file_path),
        ),
        migrations.AddField(
            model_name='note',
            name='preview_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Price to download paper (UGX)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_payments',
            field=models.BooleanField(default=False, help_text='Enable payment system (currently disabled for free trial)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='view_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Price to view full paper (UGX)', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('view', 'View Access'), ('download', 'Download Access')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('admin', 'Admin Grant')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paperflow.note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paperflow.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'note', 'payment_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('preview', 'Preview Only'), ('view', 'Full View'), ('download', 'Download')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='paperflow.note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='paperflow.student')),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('student', 'note', 'access_type')},
            },
        ),
    ]
